### ISSUE TITLE
Pixel position is incorrectly computed from index

### ISSUE THREAD

**Issue by nolmoonen** [SmallVCM/SmallVCM#8]
Hi,

On line 574 of `vertexcm.hxx`, the y position of a pixel in the raster is computed from its index:
```c++
const int y = aPixelIndex / resY;
```
which I believe is wrong. This is clearly noticable with a simple demonstration, rendering with a resolution where the width is not equal to the height. For example, running the default config with a resolution of 1024x512 gives:

![before](https://user-images.githubusercontent.com/26645861/132248896-63f527aa-792c-48c4-a616-32d7473c18ee.png)

which is not a correct result. If we change this line to:
```c++
const int y = aPixelIndex / resX;
```
the render results in:

![after](https://user-images.githubusercontent.com/26645861/132248938-8d895755-a3ff-4f34-801f-747430930e93.png)

which is the correct result. This issue was introduced by the merge of pull request #2.

Kind regards,

Nol

**Comment by iliyang** [comment]
Thanks for the fix, pull request merged!
